### ISSUE TITLE
Error when msg.c contains dm

### ISSUE THREAD

**Issue by Hyye123** [the-dev-channel/mpp-hats#14]
![image](https://user-images.githubusercontent.com/100793429/216435033-b8bc205c-fc76-4669-84e3-594696715d91.png)
![image](https://user-images.githubusercontent.com/100793429/216436048-09fccd93-f852-419b-8e0a-9005e6501719.png)

**Comment by Hri7566** [comment]
Fixed in 34a8c4b5a25b0761ecfd4c25bf7d892c3d479f1d
