### ISSUE TITLE
Hats button icon

### ISSUE THREAD

**Issue by Hri7566** [the-dev-channel/mpp-hats#3]

**Comment by daniel9046** [comment]
`$("#bottom .relative").append(`<div id="hat-btn" class="ugly-button" style="bottom: 6px;position: absolute;left: 780px;">Hats</div>`)
$("#bottom .relative #hat-btn").on('click', evt => {
        openModal('#modal #modals #hats');
        //$(`#modal #modals #hats #hat-selector option[value=${currentHat}]`).attr('selected', true);
});`
Hats button in bottom
![image](https://user-images.githubusercontent.com/78708647/203553349-0f45e8e4-28cd-4ec8-85b0-f2b1f4440721.png)

**Comment by Hri7566** [comment]
don't vanish and moderator buttons go there?

**Comment by daniel9046** [comment]
yea, but normal users would see that

**Comment by Hri7566** [comment]
@Wolfy0615 uses this script, that would be an unfavorable change on his UI

**Comment by Hri7566** [comment]
also, this issue is for the addition of an icon to the button

**Comment by Hri7566** [comment]
added icon in 689bea08c83345479cbd46a4675c8ebbf765ce32
